export default {
    LOGO : require ('../../../assets/Logo.png'),
    PASSWORD: require ('../../../assets/pass.png'),
    USERNAME: require ('../../../assets/username.png'),
    GENERO: require ('../../../assets/gen.png'),
    CI: require ('../../../assets/ci.png'),
    CONTACTO: require ('../../../assets/contacto.png'),
    EMAIL: require ('../../../assets/email.png'),
    LUGAR: require ('../../../assets/lugar.png'),
    CALENDAR: require ('../../../assets/calendar.png'),
    NUMERO: require ('../../../assets/numero.png'),
    PROFESION: require ('../../../assets/profesion.png'),
    IGLESIA: require ('../../../assets/iglesia.png'),

    FONDO1: require ('../../../assets/img1.png'),
    FONDO2: require ('../../../assets/img2.png'),
    FONDO3: require ('../../../assets/img3.png'),
    IMGFONDO1: require('../../../assets/FondoAmarrillo.jpg'),
    IMGFONDO2: require('../../../assets/FondoEsmeralda.jpg'),
    IMGFONDO3: require('../../../assets/FondoRojo.jpg'),
    SETTING: require('../../../assets/settings.png'),
    LOGOUT: require('../../../assets/logout.png'),
    SPLASH: require ('../../../assets/Splash.gif'),
    USERINICIO: require ('../../../assets/UserInicio.png'),
    USERMV: require ('../../../assets/UserMV.jpg'),
    USERPAS: require ('../../../assets/UserPastores.jpg'),
    USERRES: require ('../../../assets/UserRes.jpg'),
    USERPERFIL: require('../../../assets/UserMiPerfil.jpg'),
}